project:
  type: website
  output-dir: docs

website:
  title: "Alin Morariu"
  site-url: https://a-morariu.github.io
  favicon: a-solid.svg
  navbar:
    background: dark
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog posts
    right:
      - href: Resume_AMorariu.pdf
        text: Resume
        target: _blank # open new page/tab for
      - href: CV_AMorariu.pdf
        text: CV
        target: _blank # open new page/tab for
      - about.qmd
  page-footer: 
    background: dark 
    left: Copyright 2024, Alin Morariu
    right: Built with Quarto and published with Github [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/A-Morariu/a-morariu.github.io){target=_blank}

format:
  html:
    theme: 
      light: [lux, styles.scss]
      dark: [slate, styles.scss]
    toc: true
    mermaid: 
      theme: neutral



