project:
  type: website
  output-dir: docs

website:
  title: "Alin Morariu"
  navbar:
    background: dark
    search: true
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



