project:
  type: website
  output-dir: docs

website:
  title: "Alin Morariu"
  navbar:
    background: dark
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog posts
    right:
      - href: career.qmd
        text: Resume
      - about.qmd

format:
  html:
    theme: 
      light: lux
      dark: slate
    css: styles.css
    toc: true



